### ISSUE TITLE
New view mode: rotate left (right) and fit

### ISSUE THREAD

**Issue by Soukyuu** [benoit-pierre/mcomix#1]
This is about the only thing missing for me to be able to move on from Hamana. What it does is basically rotate a vertical image either left or right and make it fit the screen size. This is especially useful when reading a single page on a rotating monitor without having to mess with X settings. 

Would be great if you could add it.

**Comment by Soukyuu** [comment]
...there is actually something similar in the Tools->Transform->Auto-rotate image, but both options do not seem to do anything on the images I tested. Using latest git snapshot.

**Comment by benoit-pierre** [comment]
Please open a bug on the [official bug tracker](https://sourceforge.net/p/mcomix/_list/tickets).

'Tools->Transform->Auto-rotate image' should indeed do what you are asking for, but the implementation is buggy, I'm looking into it.
