### ISSUE TITLE
File movement bugs

### ISSUE THREAD

**Issue by rathsky** [benoit-pierre/mcomix#3]
Also since a while MComix loading of the preceding/following archive/folder is bugged, especially when the user moves quickly (eg: open, End key, Arrow key forward, repeat quickly).

I can't properly describe when it happens, but symptoms are eg. MComix forgetting its CWD or switching to another folder to look for archives when its CWD still has more.

**Comment by benoit-pierre** [comment]
Please open a bug on the [official bug tracker](https://sourceforge.net/p/mcomix/_list/tickets).

Don't forget to mention the version your using.
